services:
  web:
    build: .
    command: gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/portfolio.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    networks:
      - app-network

networks:
  app-network:
    name: custom_network_name  # Define your desired network name
    driver: bridge
