services:
  web:
    build: .
    command: gunicorn portfolio.wsgi:application --bind 127.0.0.1:8000
    volumes:
      - .:/app
    expose:
      - "8000"
    environment:
      - DEBUG=False
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/portfolio.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static  # Link the static files directory
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network

  db:
    image: nouchka/sqlite3:latest  # No need for a port
    volumes:
      - ./db.sqlite3:/app/db.sqlite3  # Mount the SQLite file as a volume
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
